### ISSUE TITLE
gto output name

### ISSUE THREAD

**Issue by mzechmeister** [mlafarga/raccoon#5]
Please change this line
https://github.com/mlafarga/raccoon/blob/a1e9d209a0e4f54a7a903ff0f93f9cf9b6ba039e/raccoon/scripts/ccfcompute.py#L1628
to:
```python
filout = os.path.join(args.dirout, args.obj + '.' + os.path.basename(os.path.splitext(obs)[0]) + '.ccf.dat')
```

**Comment by mlafarga** [comment]
Done!

**Comment by mzechmeister** [comment]
I see (90cd3ae6fb93dd99df89afe0fe4f570ef3d297b0). Thanks.
